apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: v-spring-kafka-producer
  name: v-spring-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-spring-kafka-producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: v-spring-kafka-producer
    spec:
      containers:
      - image: v-labs/v-spring-kafka-producer
        imagePullPolicy: Never
        name: v-spring-kafka-producer
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: v-spring-kafka-producer
  name: v-spring-kafka-producer
spec:
  ports:
  - name: 9000-9000
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: v-spring-kafka-producer
  type: ClusterIP
status:
  loadBalancer: {}
